CREATE TABLE [dbo].[subscription] (
    [subscription_id]                 INT           IDENTITY (1, 1) NOT NULL,
    [legal_entity_name]               VARCHAR (MAX) NULL,
    [pseudonym]                       VARCHAR (MAX) NULL,
    [Country_incorporation]           INT           NULL,
    [tax_residential_Status]          INT           NULL,
    [body_corporates]                 VARCHAR (MAX) NULL,
    [is_charitable_or_non_profitable] INT           DEFAULT ((1)) NULL,
    [registationid]                   INT           NULL,
    [emailid]                         VARCHAR (MAX) NULL,
    [industry]                        VARCHAR (MAX) NULL,
    [company_HQ_location]             VARCHAR (MAX) NOT NULL,
    [PAN]                             VARCHAR (MAX) NOT NULL,
    [is_pan_attached]                 INT           DEFAULT ((0)) NOT NULL,
    [PAN_COMMENTS]                    VARCHAR (MAX) NULL,
    [GST]                             VARCHAR (MAX) NOT NULL,
    [GST_COMMENTS]                    VARCHAR (MAX) NULL,
    [URL]                             VARCHAR (MAX) NULL,
    [Address]                         VARCHAR (MAX) NULL,
    [is_ey_disclosure_accepted]       INT           DEFAULT ((0)) NOT NULL,
    [STATUS]                          VARCHAR (MAX) DEFAULT ('NEW') NOT NULL,
    [pace_id]                         VARCHAR (MAX) NULL,
    [is_additional_doc_required]      INT           DEFAULT ((0)) NOT NULL,
    [created_date]                    DATETIME      DEFAULT (getdate()) NULL,
    [updated_date]                    DATETIME      NULL,
    [is_online_engaged_signed]        INT           DEFAULT ((0)) NOT NULL,
    [role_id]                         INT           NULL,
    [worked_With_EY] INT NULL DEFAULT 0, 
    [EY_Contact_Person_1] VARCHAR(MAX) NULL, 
    [EY_Contact_Person_2] VARCHAR(MAX) NULL, 
    [ROCA_Service_Availed] INT NULL DEFAULT 0, 
    [related_party_name1] VARCHAR(MAX) NULL, 
    [related_party_name2] VARCHAR(MAX) NULL, 
    PRIMARY KEY CLUSTERED ([subscription_id] ASC)
);


