CREATE TABLE [dbo].[RocaUserRegistration] (
    [Id]                 INT           NOT NULL,
    [legal_entity_name]  VARCHAR (MAX) NULL,
    [contact_person]     VARCHAR (MAX) NULL,
    [role_id]            INT           NULL,
    [emailid]            VARCHAR (MAX) NULL,
    [mobile number]      NUMERIC (10)  NULL,
    [industry_id]        INT           NULL,
    [password]           VARCHAR (10)  NULL,
    [is_email_Verified]  INT           NULL,
    [is_mobile_verified] INT           NULL,
    PRIMARY KEY CLUSTERED ([Id] ASC)
);


/*
Deployment script for roca

This code was generated by a tool.
Changes to this file may cause incorrect behavior and will be lost if
the code is regenerated.
*/

GO
SET ANSI_NULLS, ANSI_PADDING, ANSI_WARNINGS, ARITHABORT, CONCAT_NULL_YIELDS_NULL, QUOTED_IDENTIFIER ON;

SET NUMERIC_ROUNDABORT OFF;


GO
:setvar DatabaseName "roca"
:setvar DefaultFilePrefix "roca"
:setvar DefaultDataPath ""
:setvar DefaultLogPath ""

GO
:on error exit
GO
/*
Detect SQLCMD mode and disable script execution if SQLCMD mode is not supported.
To re-enable the script after enabling SQLCMD mode, execute the following:
SET NOEXEC OFF; 
*/
:setvar __IsSqlCmdEnabled "True"
GO
IF N'$(__IsSqlCmdEnabled)' NOT LIKE N'True'
    BEGIN
        PRINT N'SQLCMD mode must be enabled to successfully execute this script.';
        SET NOEXEC ON;
    END


GO

IF (SELECT OBJECT_ID('tempdb..#tmpErrors')) IS NOT NULL DROP TABLE #tmpErrors
GO
CREATE TABLE #tmpErrors (Error int)
GO
SET XACT_ABORT ON
GO
SET TRANSACTION ISOLATION LEVEL READ COMMITTED
GO
BEGIN TRANSACTION
GO
PRINT N'Rename [dbo].[ROCA_USER_REGISTRATION].[emailid] to email_id';


GO
EXECUTE sp_rename @objname = N'[dbo].[ROCA_USER_REGISTRATION].[emailid]', @newname = N'email_id', @objtype = N'COLUMN';


GO
IF @@ERROR <> 0
   AND @@TRANCOUNT > 0
    BEGIN
        ROLLBACK;
    END

IF @@TRANCOUNT = 0
    BEGIN
        INSERT  INTO #tmpErrors (Error)
        VALUES                 (1);
        BEGIN TRANSACTION;
    END


GO
PRINT N'Rename [dbo].[ROCA_USER_REGISTRATION].[mobile number] to mobile_number';


GO
EXECUTE sp_rename @objname = N'[dbo].[ROCA_USER_REGISTRATION].[mobile number]', @newname = N'mobile_number', @objtype = N'COLUMN';


GO
IF @@ERROR <> 0
   AND @@TRANCOUNT > 0
    BEGIN
        ROLLBACK;
    END

IF @@TRANCOUNT = 0
    BEGIN
        INSERT  INTO #tmpErrors (Error)
        VALUES                 (1);
        BEGIN TRANSACTION;
    END


GO
PRINT N'Dropping unnamed constraint on [dbo].[industry_child_master]...';


GO
ALTER TABLE [dbo].[industry_child_master] DROP CONSTRAINT [DF__industry___is_di__5629CD9C];


GO
IF @@ERROR <> 0
   AND @@TRANCOUNT > 0
    BEGIN
        ROLLBACK;
    END

IF @@TRANCOUNT = 0
    BEGIN
        INSERT  INTO #tmpErrors (Error)
        VALUES                 (1);
        BEGIN TRANSACTION;
    END


GO
PRINT N'Dropping unnamed constraint on [dbo].[industry_parent_master]...';


GO
ALTER TABLE [dbo].[industry_parent_master] DROP CONSTRAINT [DF__industry___is_di__571DF1D5];


GO
IF @@ERROR <> 0
   AND @@TRANCOUNT > 0
    BEGIN
        ROLLBACK;
    END

IF @@TRANCOUNT = 0
    BEGIN
        INSERT  INTO #tmpErrors (Error)
        VALUES                 (1);
        BEGIN TRANSACTION;
    END


GO
PRINT N'Dropping unnamed constraint on [dbo].[ROCA_USER_REGISTRATION]...';


GO
ALTER TABLE [dbo].[ROCA_USER_REGISTRATION] DROP CONSTRAINT [DF__ROCA_USER__is_em__5812160E];


GO
IF @@ERROR <> 0
   AND @@TRANCOUNT > 0
    BEGIN
        ROLLBACK;
    END

IF @@TRANCOUNT = 0
    BEGIN
        INSERT  INTO #tmpErrors (Error)
        VALUES                 (1);
        BEGIN TRANSACTION;
    END


GO
PRINT N'Dropping unnamed constraint on [dbo].[ROCA_USER_REGISTRATION]...';


GO
ALTER TABLE [dbo].[ROCA_USER_REGISTRATION] DROP CONSTRAINT [DF__ROCA_USER__is_mo__59063A47];


GO
IF @@ERROR <> 0
   AND @@TRANCOUNT > 0
    BEGIN
        ROLLBACK;
    END

IF @@TRANCOUNT = 0
    BEGIN
        INSERT  INTO #tmpErrors (Error)
        VALUES                 (1);
        BEGIN TRANSACTION;
    END


GO
PRINT N'Creating unnamed constraint on [dbo].[industry_child_master]...';


GO
ALTER TABLE [dbo].[industry_child_master]
    ADD DEFAULT 1 FOR [is_display];


GO
IF @@ERROR <> 0
   AND @@TRANCOUNT > 0
    BEGIN
        ROLLBACK;
    END

IF @@TRANCOUNT = 0
    BEGIN
        INSERT  INTO #tmpErrors (Error)
        VALUES                 (1);
        BEGIN TRANSACTION;
    END


GO
PRINT N'Creating unnamed constraint on [dbo].[industry_parent_master]...';


GO
ALTER TABLE [dbo].[industry_parent_master]
    ADD DEFAULT 1 FOR [is_display];


GO
IF @@ERROR <> 0
   AND @@TRANCOUNT > 0
    BEGIN
        ROLLBACK;
    END

IF @@TRANCOUNT = 0
    BEGIN
        INSERT  INTO #tmpErrors (Error)
        VALUES                 (1);
        BEGIN TRANSACTION;
    END


GO
PRINT N'Creating unnamed constraint on [dbo].[ROCA_USER_REGISTRATION]...';


GO
ALTER TABLE [dbo].[ROCA_USER_REGISTRATION]
    ADD DEFAULT 0 FOR [is_email_Verified];


GO
IF @@ERROR <> 0
   AND @@TRANCOUNT > 0
    BEGIN
        ROLLBACK;
    END

IF @@TRANCOUNT = 0
    BEGIN
        INSERT  INTO #tmpErrors (Error)
        VALUES                 (1);
        BEGIN TRANSACTION;
    END


GO
PRINT N'Creating unnamed constraint on [dbo].[ROCA_USER_REGISTRATION]...';


GO
ALTER TABLE [dbo].[ROCA_USER_REGISTRATION]
    ADD DEFAULT 0 FOR [is_mobile_verified];


GO
IF @@ERROR <> 0
   AND @@TRANCOUNT > 0
    BEGIN
        ROLLBACK;
    END

IF @@TRANCOUNT = 0
    BEGIN
        INSERT  INTO #tmpErrors (Error)
        VALUES                 (1);
        BEGIN TRANSACTION;
    END


GO

IF EXISTS (SELECT * FROM #tmpErrors) ROLLBACK TRANSACTION
GO
IF @@TRANCOUNT>0 BEGIN
PRINT N'The transacted portion of the database update succeeded.'
COMMIT TRANSACTION
END
ELSE PRINT N'The transacted portion of the database update failed.'
GO
DROP TABLE #tmpErrors
GO
PRINT N'Update complete.';


GO
